# Generated by Django 3.0.6 on 2020-07-13 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=120, verbose_name='Короткий опис')),
                ('image', models.ImageField(upload_to='news_picture', verbose_name='Зображення')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
            ],
        ),
    ]
