# Generated by Django 3.0.6 on 2020-07-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_brand_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='tag',
            field=models.CharField(max_length=10, verbose_name='Тег для HTML'),
        ),
    ]
