# Generated by Django 3.0.6 on 2020-07-17 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200714_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='news_picture')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PostsImages', to='main.News')),
            ],
        ),
    ]
