# Generated by Django 3.0.6 on 2020-07-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_newsimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newsimages',
            name='images',
        ),
        migrations.AddField(
            model_name='newsimages',
            name='image',
            field=models.ImageField(null=True, upload_to='news_picture', verbose_name='Зображення'),
        ),
    ]
