# Generated by Django 3.0.6 on 2020-07-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200717_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Продукція'},
        ),
    ]
