# Generated by Django 3.0.6 on 2020-07-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200718_1738'),
        ('main', '0008_auto_20200717_1041'),
    ]

    operations = [
    ]
