# Generated by Django 3.0.6 on 2020-07-21 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200721_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roksolana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Назва Продукції')),
            ],
        ),
        migrations.CreateModel(
            name='RoksolanaImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='production_pictures', verbose_name='Фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roksolana', to='main.Roksolana')),
            ],
        ),
    ]
