# Generated by Django 3.0.6 on 2020-07-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_aqua_aquaimg_djerelna_djerelnaimg_likuvalna_likuvalnaimg_mi_miimg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aqua',
            options={'verbose_name_plural': 'Аква Фрут'},
        ),
        migrations.AlterModelOptions(
            name='aquaimg',
            options={'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='djerelna',
            options={'verbose_name_plural': 'Джерельна'},
        ),
        migrations.AlterModelOptions(
            name='djerelnaimg',
            options={'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='likuvalna',
            options={'verbose_name_plural': 'Лікувальна'},
        ),
        migrations.AlterModelOptions(
            name='likuvalnaimg',
            options={'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='mi',
            options={'verbose_name_plural': 'МИ'},
        ),
        migrations.AlterModelOptions(
            name='miimg',
            options={'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='roksolana',
            options={'verbose_name_plural': 'Роксолана'},
        ),
        migrations.AlterModelOptions(
            name='roksolanaimg',
            options={'verbose_name_plural': 'Фото'},
        ),
    ]
