# Generated by Django 3.0.6 on 2020-07-22 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200721_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Назва продукту')),
                ('brand', models.CharField(choices=[('mi', 'МИ'), ('roksolana', 'Роксолана'), ('djerelna', 'Джерельна'), ('aqua', 'Аква'), ('likuvalna', 'Лікувальна')], default='mi', max_length=10, verbose_name='Бренд')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='production_pictures', verbose_name='Зображення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.Product')),
            ],
        ),
    ]
