# Generated by Django 3.0.6 on 2020-07-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_product_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquaimg',
            name='product',
        ),
        migrations.RemoveField(
            model_name='djerelnaimg',
            name='product',
        ),
        migrations.RemoveField(
            model_name='likuvalnaimg',
            name='product',
        ),
        migrations.RemoveField(
            model_name='miimg',
            name='product',
        ),
        migrations.RemoveField(
            model_name='roksolanaimg',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Продукція'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Фото продукції'},
        ),
        migrations.DeleteModel(
            name='Aqua',
        ),
        migrations.DeleteModel(
            name='AquaImg',
        ),
        migrations.DeleteModel(
            name='Djerelna',
        ),
        migrations.DeleteModel(
            name='DjerelnaImg',
        ),
        migrations.DeleteModel(
            name='Likuvalna',
        ),
        migrations.DeleteModel(
            name='LikuvalnaImg',
        ),
        migrations.DeleteModel(
            name='Mi',
        ),
        migrations.DeleteModel(
            name='MiImg',
        ),
        migrations.DeleteModel(
            name='Roksolana',
        ),
        migrations.DeleteModel(
            name='RoksolanaImg',
        ),
    ]
