# Generated by Django 3.0.6 on 2020-08-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200722_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.CharField(help_text='Вкажіть літражі даної продукції (напр. 0.5 л, 1 л, 2 л)', max_length=50, null=True, verbose_name='Літраж'),
        ),
    ]
