# Generated by Django 3.0.6 on 2020-08-06 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_product_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Назва для фото')),
                ('img', models.ImageField(upload_to='home_pictures', verbose_name='Фото')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('mi', 'МИ'), ('roksolana', 'Роксолана'), ('djerelna', 'Джерельна'), ('aqua', 'Аква'), ('likuvalna', 'Лікувальна')], default='mi', help_text='Виберіть бренд напою', max_length=10, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Введіть назву напою', max_length=60, verbose_name='Назва продукту'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(help_text='Загрузіть фото для напою', null=True, upload_to='production_pictures', verbose_name='Зображення'),
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pict', to='main.LoadImage')),
            ],
        ),
    ]
